#  __  __ _             ____          _
# |  \/  (_)_ __   ___ / ___|___   __| | ___
# | |\/| | | '_ \ / _ \ |   / _ \ / _` |/ _ \
# | |  | | | | | |  __/ |__| (_) | (_| |  __/  
# |_|  |_|_|_| |_|\___|\____\___/ \__,_|\___|
#

# Сообщение при первом входе игрока на сервер!
msg_first_join_all: "§eИгрок §6%ник%§e впервые посетил этот сервер§7!"

# Сообщение игроку при первом заходе
msg_first_join_player: "§eПриветствуем тебя на Нашем проекте§7!\n§aЗарегистрируй свой аккаунт сообщением в чат§7!"

# Тайтл после того, как игрок авторизуется
send_title: "§lДобро §6пожаловать§7!"

# Субтайтд после того, как игрок авторизуется
send_subtitle: "§eПриятной игры§7!"

# Сообщение после удачной регистрации
msg_reg_success: "§aВы успешно зарегистрировали свой аккаунт!\n§eВаш пароль§7: §d%пароль%"

# Сообщение игроку, который получил пароль другого игрока
msg_player_pass: "§eПароль игрока §6%ник%§7: %пароль%"

# Сообщение игроку, что изменил свой пароль
msg_refresh_pass: "§aВы успешно изменили свой пароль§7.\n§aВаш пароль теперь§7: §e%пароль%"

# Сообщение игроку, что вводит неправильно пароль
msg_error_pass: "§cПароль неправильный§7!§c Попробуйте ещё раз§7!"

# Сообщение игроку, что успешно авторизовался паролем
msg_success_auth: "§aВы успешно авторизовались на сервере§7!"

# Сообщение игроку, что успешно авторизовался по айпи
msg_success_auth_ip: "§aВы успешно вошли по айпи§7."

# Использовать регистрацию в формах?(y/N)
question: "N"
